const DEMO_CONTENT = [
  "!!! [A[C]]",
  "!(DrewMark Logo){../images/drewmark-logo.svg}",
  "!!!",
  "",
  "# DrewMark Demo ::rocket:: [A[C]]",
  "",
  "> DrewMark, inspired by (Markdown){https://daringfireball.net/projects/markdown/} and (Showdown){https://github.com/showdownjs/showdown}, is a **full-featured** markup language system. This WYSIWYG editor parses markup text into  HTML !!simultaneously!!.",
  "",
  "---",
  "",
  "## Text Decorations",
  "",
  "This is **bold text**. This is %%italic text%%. This is __underline text__. This is ~~crossed-out text~~.",
  "",
  "This is !!highlighted text!!. x^^2^^ is superscript, and H<<2>>O subscript. This is @@small font@@. This is annotation {{汉字^hàn zì}}。",
  "",
  "It also supports hundreds of emojis, e.g. ::smile:: ::heart:: ::+1:: ::fire:: ::rocket:: ::tada:: ::computer:: ::bulb::",
  "---",
  "",
  "## Codes",
  "",
  "Inline code: `const msg = \"Hello, DrewMark!\";`",
  "",
  "Code block:",
  "",
  "```javascript",
  "function drewmarkParser(content, options) {",
  "  // parse DrewMark text into HTML",
  "  return parseBlocks(content.split('\\n'), options);",
  "}",
  "```",
  "",
  "---",
  "",
  "## Lists",
  "",
  "### Unordered Lists",
  "",
  "+ Disc",
  "+ Item 2",
  "  - Circle",
  "  - Item 2",
  "    * Square",
  "",
  "### Ordered Lists",
  "",
  "1. Step 1: load the script",
  "2. Step 2: load the css",
  "3. Step 3: use `drewmarkEditor()`",
  "",
  "### Task Lists",
  "",
  "+*+ To define syntax rules",
  "+*+ To develop the parser",
  "+*+ To develop the WYSIWYG editor",
  "-*- To develop the plus version",
  "",
  "---",
  "",
  "## Table",
  "",
  "| Name | Position | City |",
  "|====|====|==== [a[c]] |",
  "| Jane Smith | Front-end Engineer | SF |",
  "| Michael Brown | Back-end Engineer | LA |",
  "| John Doe | Full-stack Engineer | NY |",
  "",
  "---",
  "",
  "## Link",
  "",
  "Please visit (DrewMark){https://github.com/drewneon/drewmark=>blank} for more info",
  "",
  "The URL is easily exposed: (){https://example.com}",
  "",
  "---",
  "",
  "## Images",
  "",
  "This is an inline image !(示例图片/20/){media/demo_pic.jpg}, which can be inserted into texts.",
  "",
  "!!!",
  "! This is an image block, and this line is the caption.",
  "The text in the image lines won't show up!(example/200/200/){media/demo_pic.jpg}",
  "!!!",
  "",
  "---",
  "",
  "## Audio",
  "",
  "~(){media/demo_music.mp3|mp3}",
  "",
  "---",
  "",
  "## Video",
  "",
  "$(/300/){media/demo_vid.mp4|mp4}",
  "",
  "---",
  "",
  "## Quotes",
  "",
  "This is an inline quote: >>I have a dream ...<<",
  "",
  "This is multi-level nested quote blocks.",
  "",
  "> Level I quote",
  ">> Level II quote",
  ">>> Level III quote, supports **text decorations**",
  "",
  "---",
  "",
  "## Description List",
  "",
  ";;Term 1::description;;",
  ";;Term 2::description list, supports **text decorations**;;",
  "",
  "---",
  "",
  "## Details",
  "",
  ";;; Click to open details",
  "The detail block supports any DrewMark syntax, literarily !!**any**!!, including lists, table, and etc.",
  ";;;",
  "",
  ";;; Unfolded when loaded",
  "Just add `>` to the end of the ending markup line.",
  ";;; >",
  "",
  "---",
  "",
  "## Progress",
  "",
  "This is a progress bar: ((32//56))",
  "",
  "## Attribute Syntax",
  "",
  "[c[highlight-box]c] This paragraph has `class` attr.",
  "",
  "",
  ""
]
